### ISSUE TITLE
doors sometimes placed in wrong place

### ISSUE THREAD

**Issue by friuns2** [thelivewire/unityHalf-life#3]
![image](https://user-images.githubusercontent.com/16543239/37561050-55077720-2a4d-11e8-8e04-d86a3c5f1e42.png)

hi again, any clues where should i look to fix it?

**Comment by friuns2** [comment]
easy fixed by parsing models from text file there are cordinates

**Comment by thelivewire** [comment]
If the bsp has been edited some models might have an offset called origin in the text file, also the same model can be hacked to be used in more than one place and for other things, like a func_push could be copied and used as a trigger
